version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Map port 80 in the container to port 5000 on the host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map port 80 in the container to port 3000 on the host
    environment:
      - NEXT_PUBLIC_API_HOSTNAME=http://localhost:5000
